<a href="https://colab.research.google.com/github/mahakgarg333/CODSOFT/blob/main/TASK_2_Credit_Card_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importing the dependencies

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
#loading the dataset to a pandas dataframe
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [ ]:
#first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
15931,27369,-1.160116,-0.244177,0.744250,-0.192350,1.156356,-1.931383,0.409670,-0.364716,-0.516156,...,-0.021714,0.012447,-0.360625,0.514926,0.064194,1.026317,-0.030845,-0.083609,52.90,0.0
15932,27369,-3.058318,3.099206,-4.932555,1.924138,-1.576032,-2.135383,-0.830098,2.228617,-0.312343,...,-0.111526,-0.485223,-0.003945,0.049422,-0.173962,-0.379260,0.171872,-0.236166,99.99,0.0
15933,27369,-0.661806,0.315385,2.011194,-0.438757,-0.554990,-0.668072,0.424651,0.079141,0.126057,...,0.148063,0.177511,0.134794,0.359931,-0.544428,0.181545,0.068546,0.153438,74.58,0.0
15934,27370,1.525348,-1.231442,0.420095,-1.551218,-1.376006,0.100758,-1.455755,0.134876,-1.319056,...,-0.108619,0.084883,-0.051758,-0.815038,0.331989,-0.015837,0.058942,0.011087,6.00,0.0
15935,27371,1.385680,-0.590076,-0.569197,-0.939441,-0.196015,-0.486685,-0.102496,-0.237930,-0.928028,...,-0.255944,-1.055682,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#dataset information
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15936 entries, 0 to 15935
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    15936 non-null  int64
 1   V1      15936 non-null  float64
 2   V2      15936 non-null  float64
 3   V3      15936 non-null  float64
 4   V4      15936 non-null  float64
 5   V5      15936 non-null  float64
 6   V6      15936 non-null  float64
 7   V7      15936 non-null  float64
 8   V8      15936 non-null  float64
 9   V9      15936 non-null  float64
 10  V10     15936 non-null  float64
 11  V11     15936 non-null  float64
 12  V12     15936 non-null  float64
 13  V13     15936 non-null  float64
 14  V14     15936 non-null  float64
 15  V15     15936 non-null  float64
 16  V16     15936 non-null  float64
 17  V17     15936 non-null  float64
 18  V18     15936 non-null  float64
 19  V19     15936 non-null  float64
 20  V20     15936 non-null  float64
 21  V21     15936 non-null  float64
 22  V22     15936 non-null  float64
 23  V23     15935 non-null  float64
 24  V24     15935 non-null  float64
 25  V25     15935 non-null  float64
 26  V26     15935 non-null  float64
 27  V27     15935 non-null  float64
 28  V28     15935 non-null  float64
 29  Amount  15935 non-null  float64
 30  Class   15935 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 3.8 MB

In [ ]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

0: legit transaction


1: fraudulent transaction


```
# This is formatted as code
```

In [ ]:
#distribution of legit transaction and fradulent transactions
credit_card_data['Class'].value_counts()

0.0    15862
1.0       73
Name: Class, dtype: int64

This dataset is highly unbalanced. We can not feed our model this dataset. So we need to make some of the changes.


0 --> Normal transaction

1--> Fradulent transaction

In [ ]:
#separating the data for analysis
#here we have created 2 variables legit and fraud.
legit = credit_card_data[credit_card_data.Class==0]
fraud = credit_card_data[credit_card_data.Class==1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(15862, 31)
(73, 31)

In [ ]:
#statistical measures of the data
legit.Amount.describe()

count    15862.000000
mean        66.280151
std        188.898885
min          0.000000
25%          5.522500
50%         15.950000
75%         53.890000
max       7712.430000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count      73.000000
mean       90.307123
std       271.634360
min         0.000000
25%         1.000000
50%         1.000000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
#compare the values of both transactions
#comparing mean values
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,12104.432165,-0.219072,0.25000,0.862854,0.272641,-0.105868,0.124522,-0.112681,-0.016178,0.879120,...,0.028173,-0.064056,-0.161585,-0.035040,0.013076,0.117023,0.037111,0.011206,0.005907,66.280151
1.0,15559.643836,-7.929807,6.19312,-11.997831,6.555050,-5.474984,-2.480356,-8.354317,3.668478,-3.086988,...,0.671905,0.441100,-0.295856,-0.358994,-0.328925,0.216076,0.209323,0.927187,0.061380,90.307123

Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and fradulent transactions.

No of fradulent transactions --> 173

In [ ]:
legit_sample = legit.sample(n=173)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Concatenating two dataframes

In [ ]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
14992,26317,1.245674,0.166975,0.488306,0.635322,-0.562777,-1.011073,0.014953,-0.160211,0.170362,...,-0.262581,-0.816264,0.140304,0.357827,0.186423,0.096544,-0.035866,0.018495,8.99,0.0
9772,14489,1.264584,-0.028245,0.506868,0.074501,-0.191959,0.120922,-0.497117,-0.041140,1.711010,...,-0.088517,0.073184,-0.095232,-0.735728,0.263980,1.111369,-0.070378,-0.005164,14.95,0.0
5645,5870,-0.547144,-2.838037,0.831175,2.541714,-1.971937,0.808559,0.098420,0.060099,2.348956,...,0.466015,0.114777,-0.880794,0.569548,0.300682,-0.280128,-0.096719,0.163220,841.96,0.0
11811,20277,1.206300,-0.230347,1.186298,-0.440323,-1.266400,-0.950477,-0.614414,-0.162249,3.016781,...,-0.129824,0.118054,0.001616,0.687105,0.444311,-0.748011,0.068140,0.035013,11.85,0.0
15914,27348,1.012816,-0.626216,0.416264,0.486541,-0.742699,0.049411,-0.338169,0.062332,-1.337575,...,-0.280929,-0.599352,-0.009526,-0.027785,0.247413,-0.448223,0.039052,0.039950,128.00,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
15566,26961,-23.237920,13.487386,-25.188773,6.261733,-17.345188,-4.534989,-17.100492,15.374630,-3.845567,...,1.769708,-1.691973,-1.045673,0.143386,1.611577,-0.221576,1.481233,0.438125,99.99,1.0
15736,27163,-23.914101,13.765942,-25.733734,6.290918,-17.784824,-4.572498,-17.390764,15.794136,-3.819832,...,1.773399,-1.748426,-1.093104,0.147807,1.663792,-0.221024,1.458076,0.430315,99.99,1.0
15751,27187,-24.590245,14.044567,-26.278701,6.320089,-18.224513,-4.609968,-17.681003,16.213627,-3.794093,...,1.777063,-1.804874,-1.140605,0.152234,1.715997,-0.220471,1.434951,0.422492,99.99,1.0
15781,27219,-25.266355,14.323254,-26.823673,6.349248,-18.664251,-4.647403,-17.971212,16.633103,-3.768351,...,1.780701,-1.861318,-1.188167,0.156667,1.768192,-0.219916,1.411855,0.414656,99.99,1.0
15810,27252,-25.942434,14.601998,-27.368650,6.378395,-19.104033,-4.684806,-18.261393,17.052566,-3.742605,...,1.784316,-1.917759,-1.235787,0.161105,1.820378,-0.219359,1.388786,0.406810,99.99,1.0

In [ ]:
new_dataset['Class'].value_counts()

0.0    173
1.0     73
Name: Class, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,11301.982659,-0.340584,0.492688,0.729718,0.181241,-0.104975,0.097657,-0.110413,-0.079490,0.973999,...,-0.029384,-0.024328,-0.284629,-0.013561,0.063419,0.124237,0.056673,0.022658,0.032263,50.340231
1.0,15559.643836,-7.929807,6.193120,-11.997831,6.555050,-5.474984,-2.480356,-8.354317,3.668478,-3.086988,...,0.671905,0.441100,-0.295856,-0.358994,-0.328925,0.216076,0.209323,0.927187,0.061380,90.307123

Splitting the data into features and targets

In [ ]:
X = new_dataset.drop(columns ='Class', axis=1)
Y = new_dataset['Class']

In [ ]:
print(X)

        Time         V1         V2         V3        V4         V5        V6  \
14992  26317   1.245674   0.166975   0.488306  0.635322  -0.562777 -1.011073
9772   14489   1.264584  -0.028245   0.506868  0.074501  -0.191959  0.120922
5645    5870  -0.547144  -2.838037   0.831175  2.541714  -1.971937  0.808559
11811  20277   1.206300  -0.230347   1.186298 -0.440323  -1.266400 -0.950477
15914  27348   1.012816  -0.626216   0.416264  0.486541  -0.742699  0.049411
...      ...        ...        ...        ...       ...        ...       ...
15566  26961 -23.237920  13.487386 -25.188773  6.261733 -17.345188 -4.534989
15736  27163 -23.914101  13.765942 -25.733734  6.290918 -17.784824 -4.572498
15751  27187 -24.590245  14.044567 -26.278701  6.320089 -18.224513 -4.609968
15781  27219 -25.266355  14.323254 -26.823673  6.349248 -18.664251 -4.647403
15810  27252 -25.942434  14.601998 -27.368650  6.378395 -19.104033 -4.684806

              V7         V8        V9  ...       V20       V21       V22  \
14992   0.014953  -0.160211  0.170362  ... -0.132080 -0.262581 -0.816264
9772   -0.497117  -0.041140  1.711010  ... -0.054238 -0.088517  0.073184
5645    0.098420   0.060099  2.348956  ...  1.486916  0.466015  0.114777
11811  -0.614414  -0.162249  3.016781  ... -0.129583 -0.129824  0.118054
15914  -0.338169   0.062332 -1.337575  ... -0.307513 -0.280929 -0.599352
...          ...        ...       ...  ...       ...       ...       ...
15566 -17.100492  15.374630 -3.845567  ...  1.630787  1.769708 -1.691973
15736 -17.390764  15.794136 -3.819832  ...  1.640037  1.773399 -1.748426
15751 -17.681003  16.213627 -3.794093  ...  1.649202  1.777063 -1.804874
15781 -17.971212  16.633103 -3.768351  ...  1.658289  1.780701 -1.861318
15810 -18.261393  17.052566 -3.742605  ...  1.667304  1.784316 -1.917759

            V23       V24       V25       V26       V27       V28  Amount
14992  0.140304  0.357827  0.186423  0.096544 -0.035866  0.018495    8.99
9772  -0.095232 -0.735728  0.263980  1.111369 -0.070378 -0.005164   14.95
5645  -0.880794  0.569548  0.300682 -0.280128 -0.096719  0.163220  841.96
11811  0.001616  0.687105  0.444311 -0.748011  0.068140  0.035013   11.85
15914 -0.009526 -0.027785  0.247413 -0.448223  0.039052  0.039950  128.00
...         ...       ...       ...       ...       ...       ...     ...
15566 -1.045673  0.143386  1.611577 -0.221576  1.481233  0.438125   99.99
15736 -1.093104  0.147807  1.663792 -0.221024  1.458076  0.430315   99.99
15751 -1.140605  0.152234  1.715997 -0.220471  1.434951  0.422492   99.99
15781 -1.188167  0.156667  1.768192 -0.219916  1.411855  0.414656   99.99
15810 -1.235787  0.161105  1.820378 -0.219359  1.388786  0.406810   99.99

[246 rows x 30 columns]

In [ ]:
print(Y)

14992    0.0
9772     0.0
5645     0.0
11811    0.0
15914    0.0
        ...
15566    1.0
15736    1.0
15751    1.0
15781    1.0
15810    1.0
Name: Class, Length: 246, dtype: float64

Split the data into training data and testing data

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(246, 30) (196, 30) (50, 30)

Model training

Logistic regression

In [ ]:
model = LogisticRegression()

In [ ]:
#training the logistic regression model with training data
model.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation


Accuracy score

In [ ]:
#accuracy on training data

In [ ]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
print("Accuracy on training data:", training_data_accuracy)

Accuracy on training data: 0.9897959183673469

In [ ]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [ ]:
print("Accuracy on testing data:", test_data_accuracy)

Accuracy on testing data: 0.98